name: Scrape

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      STATE_FILE: state.json
      RESULT_FILE: README.md
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run export-dids script
        run: deno run -A ./scripts/export-dids.ts

      - name: Run check-online script
        run: deno run -A ./scripts/check-online.ts

      - name: Run generate-markdown script
        run: deno run -A ./scripts/generate-markdown.ts

      - name: Push to repository
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add README.md state.json
          git commit -m "update: $(date --iso-8601=seconds)" || exit 0
          git push
